import numpy as np
from .. import Globals

datapath = Globals.DataPath + 'Fields/{:s}/' #.format(sc)


#data type for combined E and B data
dtype = [	('Date','int32'),
			('ut','float32'),
			('utc','float64'),
			('BxGSE','float32'),
			('ByGSE','float32'),
			('BzGSE','float32'),
			('BxGSM','float32'),
			('ByGSM','float32'),
			('BzGSM','float32'),
			('BxSM','float32'),
			('BySM','float32'),
			('BzSM','float32'),
			('BxP','float32'),
			('ByT','float32'),
			('BzC','float32'),
			('ExGSE','float32'),
			('EyGSE','float32'),
			('EzGSE','float32'),
			('ExGSM','float32'),
			('EyGSM','float32'),
			('EzGSM','float32'),
			('ExSM','float32'),
			('EySM','float32'),
			('EzSM','float32'),
			('ExP','float32'),
			('EyT','float32'),
			('EzC','float32'),
			('BzBx','float32'),
			('ByBx','float32'),
			('MlatN','float32'),
			('MlatS','float32'),
			('GlatN','float32'),
			('GlatS','float32'),
			('MlonN','float32'),
			('MlonS','float32'),
			('GlonN','float32'),
			('GlonS','float32'),
			('MltN','float32'),
			('MltS','float32'),
			('GltN','float32'),
			('GltS','float32'),
			('MltE','float32'),
			('Lshell','float32'),
			('FlLen','float32'),
			('Rmax','float32'),
			('Rnorm','float32'),
			('Tilt','float32'),
			('Xgse','float32'),
			('Ygse','float32'),
			('Zgse','float32'),
			('Xgsm','float32'),
			('Ygsm','float32'),
			('Zgsm','float32'),
			('Xsm','float32'),
			('Ysm','float32'),
			('Zsm','float32')]
